version: 2.2.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
environment:
  REDIS_PATH: C:\Users\appveyor\.nuget\packages\redis-64\3.0.503\tools
before_build:
- cmd: nuget restore
build:
  verbosity: normal
after_build:
- cmd: >-
    dotnet pack --no-build -c Release RedLock.SERedis\RedLock.SERedis.csproj /p:PackageOutputPath=.nupkgs
before_test:
- ps: >-
    cd RedLockNet.Tests\RedisConfig

    Start-Process run-all-servers.cmd

    Start-Sleep 5
artifacts:
- path: '**\.nupkgs\*.nupkg'